/* create databases */
CREATE DATABASE IF NOT EXISTS CAMAGRU;

/* create table */
USE CAMAGRU;

CREATE TABLE IF NOT EXISTS members (
	id INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
	login VARCHAR(255) NOT NULL,
	mail VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	token VARCHAR(255) NOT NULL,
	actif TINYINT(1) DEFAULT NULL,
	create_date DATETIME NOT NULL,
	PRIMARY KEY (id)
);